// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
  RequiredParams
} from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales = 'zh' | 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
  about: string
  advanced: string
  basic: string
  cancel: string
  choose_a_color: string
  color: string
  connect: string
  connection_established: string
  copy_my_connection_string: string
  disconnect: string
  fullscreen: string
  host_a_session: string
  host_connection_string: string
  hosting_a_session: string
  is_microphone_active_on_connect: string
  join_a_session: string
  joined_a_session: string
  media: string
  microphone_active: string
  microphone_inactive: string
  not_streaming_your_display: string
  participant_connection_string: string
  remote_cursors_disabled: string
  remote_cursors_enabled: string
  save: string
  session_started: string
  settings: string
  start_a_new_session: string
  streaming_your_display: string
  stun_turn_server_objects: string
  username: string
  zoom_in: string
  zoom_out: string
}

export type TranslationFunctions = {}

export type Formatters = {}
