---
name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up env
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "PLATFORM=linux" >> $GITHUB_ENV
      - name: Install OS packages
        run: |
          sudo apt-get install -y flatpak flatpak-builder && \
          flatpak remote-add \
            --user \
            --if-not-exists \
            flathub https://flathub.org/repo/flathub.flatpakrepo
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install node dependencies
        run: npm ci
      - name: Build Linux
        run: ./scripts/build.sh
      - name: Linux Release
        run: ./scripts/release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up env
        shell: bash
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "PLATFORM=windows" >> $GITHUB_ENV
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install node dependencies
        run: npm ci
      - name: Build Windows
        shell: bash
        run: ./scripts/build.sh
      - name: Windows Release
        shell: bash
        run: ./scripts/release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-macos:
    name: Build MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install bash
        run: brew install bash
      - name: Set up env
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "PLATFORM=macos" >> $GITHUB_ENV
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install node dependencies
        run: npm ci
      - name: Build MacOS
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_NOTARIZATION_WEBHOOK_URL: ${{ secrets.APPLE_NOTARIZATION_WEBHOOK_URL }}
        run: ./scripts/build.sh
      - name: MacOS Release
        run: ./scripts/release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
